### ISSUE TITLE
Not able to get cost details while running the script

### ISSUE THREAD

**Issue by VikashPratheepan** [Zipstack/unstract-api-deployments-batch-run#5]
Need to add "include_metadata" flag as a command line input and it should be optional

**Comment by ritwik-g** [comment]
@muhammad-ali-e we should include the token count and cost in the final detailed report. Which is not handled in the above PR I guess.

**Comment by ritwik-g** [comment]
The metadata output contains multiple entries for each model. We need to consider adding support for a detailed report which can include this as well. An HTML based report might be more apt for this. 
```
"embedding": [
    {
        "cost_in_dollars": "0.0000003",
        "embedding_tokens": 3,
        "model_name": "text-embedding-ada-002"
    }
],
"extraction_llm": [
    {
        "cost_in_dollars": "0.07063",
        "input_tokens": 4636,
        "model_name": "gpt-4-1106-preview",
        "output_tokens": 809,
        "total_tokens": 5445
    }
],
```

But as an initial version we can add the sum of all cost in the detailed report table
